version: 3  #  version 3 similar to 2 but support docker swarm
services:
  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgres:9.4
    networks:
      - back-end

  vote:
    image: voting-app
    build: ./vote
    ports:
    - 5000: 80
    depends_on:
      - redis
    networks:
      - front-end
      - back-end

  result:
    build: ./result
    image: result-app
    ports:
    - 5001: 80
    depends_on:
      - db
    networks:
      - front-end
      - back-end

  worker:
    build: ./worker
    image: worker
    depends_on:
      - db
      - redis
    networks:
      - back-end


networks:
  front-end:
  back-end: